### ISSUE TITLE
Semi-Bug: No Done Button when no Shades are Selected

### ISSUE THREAD

**Issue by cgmckeever** [bujvary/hubitat#2]
This might be counter-intuitive, but if you do not select a Shade to sync, you can not save the app. 
Why would I do this? I only want scenes because (it appears) I cant get tilt directly from the shade-device.

<img width="730" alt="Screen Shot 2022-01-06 at 8 28 29 AM" src="https://user-images.githubusercontent.com/513738/148398223-62cd702e-d320-49eb-a436-75588aab3931.png">

**Comment by bujvary** [comment]
The Hunter Douglas Powerview app has been updated to allow the user to complete the setup if either shades or scenes are selected. Please use HPM to update the package on your hub.

The shade driver does not currently support tilt operations as I don't have any Hunter Douglas shades that tilt so I have no way of testing the capability. If you are willing to test I can look into adding tilt control.

Can you tell me what shades you have?

**Comment by cgmckeever** [comment]
Love the turn around .. thank you ! .. I have Pirouettes

**Comment by cgmckeever** [comment]
also, where it your tip jar .. you sir, deserve a drink!

**Comment by bujvary** [comment]
This was any easy fix!

I'd looked at it a year ago and I don't think it will be a lot of work. If you are willing to test the changes open a new issue for tilt control capability and I'll get working on it.
