### ISSUE TITLE
Feature Request: Tilt Control

### ISSUE THREAD

**Issue by cgmckeever** [bujvary/hubitat#3]
Send more some changes, I can try the tilt control .... if its a pain-in-the-ass, my tilt-scene does all I need

**Comment by bujvary** [comment]
I have a Hunter Douglas Powerview BETA package available via HPM. I assume you already have my package repository setup as a custom repository in HPM?

I created a separate BETA package to install so that you could test without breaking any of your current automations. Once installed and setup, it will create a second set of Hunter Douglas devices with "-beta" for the DNI. The shade devices will have new tilt control options:

- Set Tilt Position
- Tile Close
- Tilt Open

I think I updated everything that needed to be updated for tilt control. Unfortunately, I don't have tilt shades so I'm limited in the testing that I can do. While testing on your hub please ensure debug is on for both the HD Powerview App and for the shade you are testing with. If things aren't working as expected provide the debug log so that I can try and figure out what's wrong.

Thanks for your help in testing this!

**Comment by cgmckeever** [comment]
NICE -- I can test this weekend!

**Comment by cgmckeever** [comment]
First thing I noticed is that its not finding State values for me .. where as the original version does (same shade). I have also calibrated 

<img width="434" alt="Screen Shot 2022-01-07 at 9 28 56 PM" src="https://user-images.githubusercontent.com/513738/148630072-1a50785d-5e35-4c4a-af9c-7e76fabaa58e.png">

I manually selected 

<img width="316" alt="Screen Shot 2022-01-07 at 9 43 45 PM" src="https://user-images.githubusercontent.com/513738/148630383-b0a23a6c-e552-41cb-997b-be2a18836f00.png">

Nothing seems to Tilt

`Tile Open` raised the bottom 3 inches off the bottom

`Set Tilt Position` `50` also raises it 3 inches

`Tilt Close` works, but I think thats cause its just a `Close` anyhows

**Comment by cgmckeever** [comment]
also - there were no events in the log

**Comment by cgmckeever** [comment]
actually .. 
```
dev:2782022-01-07 10:09:22.471 pm debugtiltClose()
dev:2782022-01-07 10:08:50.140 pm debugtiltClose()
dev:2782022-01-07 10:08:40.992 pm debugtiltOpen()
```

**Comment by bujvary** [comment]
Ok I'll take a look at the code.  I'm not sure why State variables aren't correct. Can you turn debug on in the app so I can see what is being sent to the Powerview hub. The debug option in the app will disable after 15 minutes so the logs don't fill up. I need to update the app to say that.

**Comment by cgmckeever** [comment]
I had turned it on and all I got were the 3 debug messages above ---^

**Comment by bujvary** [comment]
Those debug messages are from the shade driver, there should be debug messages from the app that shows the communication with the powerview hub.

**Comment by cgmckeever** [comment]
AHH DUMB DUMB ... in the app .. got it .. getting some now

**Comment by cgmckeever** [comment]
```
app:4062022-01-08 02:02:05.982 pm debugsetPositionCallback for shadeId 964, calling device null
app:4062022-01-08 02:02:05.979 pm debugjson: [shade:[capabilities:1, batteryStrength:149, smartPowerSupply:[port:0, id:0, status:0], batteryKind:0, batteryStatus:3, groupId:869, name:TGl2aW5nIFJvb20gRnJvbnQgU2hhZGU=, positions:[position1:1, posKind1:3], id:964, type:18, firmware:[subRevision:2, build:2767, index:9, revision:2], roomId:15448]]
app:4062022-01-08 02:02:05.975 pm debugEntered setPositionCallback()...
app:4062022-01-08 02:02:04.281 pm debugSending HubAction: PUT /api/shades/964-beta HTTP/1.1
Accept: */*
User-Agent: Linux UPnP/1.0 Hubitat
HOST: 192.168.2.149:80
Content-Type: application/json
Content-Length: 52

{"shade":{"positions":{"posKind1":3,"position1":1}}}
app:4062022-01-08 02:02:04.277 pm debugcallPowerView: url = 'http://192.168.2.149:80/api/shades/964-beta', method = 'PUT', body = '{"shade":{"positions":{"posKind1":3,"position1":1}}}', query = null, callback = setPositionCallback
app:4062022-01-08 02:02:04.274 pm debugsetPosition: shadeDevice = Living Room Front, positions = [tiltPosition:0]
app:4062022-01-08 02:01:46.715 pm debugsetPositionCallback for shadeId 964, calling device null
app:4062022-01-08 02:01:46.706 pm debugjson: [shade:[capabilities:1, batteryStrength:149, smartPowerSupply:[port:0, id:0, status:0], batteryKind:0, batteryStatus:3, groupId:869, name:TGl2aW5nIFJvb20gRnJvbnQgU2hhZGU=, positions:[position1:32768, posKind1:3], id:964, type:18, firmware:[subRevision:2, build:2767, index:9, revision:2], roomId:15448]]
app:4062022-01-08 02:01:46.702 pm debugEntered setPositionCallback()...
app:4062022-01-08 02:01:45.040 pm debugSending HubAction: PUT /api/shades/964-beta HTTP/1.1
Accept: */*
User-Agent: Linux UPnP/1.0 Hubitat
HOST: 192.168.2.149:80
Content-Type: application/json
Content-Length: 56

{"shade":{"positions":{"posKind1":3,"position1":32768}}}
app:4062022-01-08 02:01:45.036 pm debugcallPowerView: url = 'http://192.168.2.149:80/api/shades/964-beta', method = 'PUT', body = '{"shade":{"positions":{"posKind1":3,"position1":32768}}}', query = null, callback = setPositionCallback
app:4062022-01-08 02:01:45.011 pm debugsetPosition: shadeDevice = Living Room Front, positions = [tiltPosition:50]
--- Live Log Started, waiting for events ---
```

**Comment by bujvary** [comment]
Perfect. I'll look at why the state variables aren't populating first. Hopefully that will fix whatever else is going on.

**Comment by bujvary** [comment]
I finally was able to get back to this. I figured out why the state variables weren't being set and I made some additional tilt control changes.  Hopefully this will work. The new version 2.0.1 is available via HPM.

**Comment by cgmckeever** [comment]
I will get to this hopefully tomorrow evening .. THANKS!!!

**Comment by bujvary** [comment]
There is a new version of the beta package, v2.0.2. I fixed some issues with top-down/bottom-up shades as well as refactoring the open/close/tilt_open/tilt_close functions to streamline them.

**Comment by cgmckeever** [comment]
I think you got it!

- State Variables appear
- Set Tilt Position lets you specify amotun
- Tilt Open Fully opens the tilt
- Tilt Close closes (although this is basically just a close in general) 

Did I miss testing anything else?

**Comment by bujvary** [comment]
I think that covers everything. Glad it's working. Once the top-down/bottom-up changes have been tested by another person I'll move the release from beta to production.

Thanks for your help with testing!

**Comment by bujvary** [comment]
Testing of top-down/bottom-up shade chages have been completed. the At this point the beta package is going away and the changes have been moved to the production Hunter Douglas Powerview package. The new production version will be v2.1.0.

**Comment by cgmckeever** [comment]
Nice work ... !!!! Ill close this issue
