### ISSUE TITLE
error determining closed state

### ISSUE THREAD

**Issue by rvrolyk** [bujvary/hubitat#4]
with a top-down/bottom-up shade (maybe other types but I'm not familiar w/ them) there's a small glitch determining closed state.  If the top rail is closed but the bottom is open (or the reverse) then which rail is in positions.posKind2 "wins" and determines the overall closed state.  This means if posKind1 is bottom and posKind2 is top and the bottom is 100 and top is 0 (fully open) the state will still be closed.

My quick hack to fix this is to alter the else clause in `updatePosition` like this:

```
	else {
        // A TD/BU shade is only closed if both rails are closed so check the other rail first.
        if (state.capabilities == 7 && (posKind == 1 /* bottom */ && device.currentValue('topPosition') > 0)
            || (posKind == 2 /* top */ && device.currentValue('bottomPosition') > 0)) {
            // one of them is still open, do nothing
            if (logEnable) log.debug "Top-down/Bottom-up blind still open"
            return
        }
            
	    sendEvent(name: "windowShade", value: "closed", displayed:true)
            sendEvent(name: "switch", value: "off")
	}
```

However, I suspect it may be a bit cleaner to try to change the call order in `handleEvent` so higher position values are parsed last?

**Comment by bujvary** [comment]
I'll take a look at this, I only have top down shades so I had no way to test this so I never went very far with making sure the closed state for all shade types were correct.

**Comment by rvrolyk** [comment]
No worries and thanks for the work on this!  If you need testing with td/bu
I'm happy to help (I have those and normal bottom up).  Aside from the
oddity you'd expect trying to use td/bu via voice and the closed state it
works great so far.  The only other thing I think would be nice is if the
level value was only representing one of the directions - it's a bit funny
to see level: 100 and windowShade: closed because it picked the level for
the top rail.  I'm not sure picking one to correlate to level is the best
answer but it's at least easy to understand.

**Comment by bujvary** [comment]
The top down bottom up shade is weird when it comes to setting open/closed state and level. I'll see what I can do.  Maybe add a preference for which rail to use for the level state?

**Comment by rvrolyk** [comment]
preference makes sense to me; I can imagine a user may want to use the top
rail if that's what they often move...

Open/close is a bit easier to conceptualize but makes the code a bit tricky
since it has to consider both rail positions to actually determine the true
state which is odd compared to the other single movement types.

**Comment by bujvary** [comment]
I have a Hunter Douglas Powerview BETA package available via HPM. I assume you already have my package repository setup as a custom repository in HPM?

I created a separate BETA package to install so that we could test new funcitonality/changes without breaking any current automations. Once installed and setup, it will create a second set of Hunter Douglas devices with "-beta" for the DNI.

There is a new version of the beta package, v2.0.2. I fixed the issues you identified with top-down/bottom-up shades as well as refactoring the open/close/tilt_open/tilt_close functions to streamline them.

I did as much testing as I could on my end. Let me know how it goes.

**Comment by rvrolyk** [comment]
that seems to be working fine for me.  It properly tracks level based on the rail I select and the open/close issue seems gone.

 I ran into one glitch which is that out of the box the blind hasn't set the `railForLevelState` state so there's a null pointer on line 244 and 248.  The way this works in HE is a bit unfortunate as I think it doesn't set the default until the preference is used because it's guarded by the conditional block.  I seem to recall having a similar problem in an app I wrote and I needed to use another variable to track the true value and have a default for that which was overridden by the preference if it was non-null.

**Comment by bujvary** [comment]
Yeah I've hit that in other drivers I've written and didn't think about that here. I'll get that fixed. I'm also refactoring some of the code so when I'm done if you don't mind testing it I'd appreciate it.

**Comment by rvrolyk** [comment]
Sure, just let me know when you’re ready. I’m going to be out of town over
the long weekend but am happy to test next week.

**Comment by bujvary** [comment]
There is a new beta version available v2.0.3 in HPM. When you have a chance can you test it with your TD/BU shades. I refactored that code to better handle setting the windowShade state.

**Comment by rvrolyk** [comment]
I had it create a new device and things look good, no more
NullPointerException and commands seem ok.

**Comment by rvrolyk** [comment]
not a huge deal but as an FYI - trying to use HPM to remove the beta causes
it to attempt to remove the non-beta.  I think this is because the app and
driver names are unchanged and I suspect the keys used to track them
exclude the package name and not use the hex id.  I suspect changing the
names would fix this if you wanted to.

**Comment by bujvary** [comment]
Thanks for the heads up about removing the beta from via HPM. At this point the beta package is going away and the changes have been moved to the production Hunter Douglas Powerview package. The new production version will be v2.1.0.

**Comment by rvrolyk** [comment]
cool, thanks for updating it!
