### ISSUE TITLE
Return false instead of throwing exception for missing capability 

### ISSUE THREAD

**Issue by howardic** [bujvary/hubitat#8]
I have Applause Bottom Up skylight shades.

Your capability checking seems way too aggressive. In particular, you have these nice supportsXXX functions, which for some strange reason throw an exception for an unsupported capability rather than returning false. I have horizontal shades that just open and close, yet the latest version of the hub returns secondaryPosition and tiltPosition as 0. In order to not get an error, I have to select a specific shade version that has this support, even though mine don't.

I can understand wanting to throw the exception for debugging purposes, but leaving it in the code seems like a mistake. The exception prevents further processing, which in this case is a bad thing.

In hunter-douglas-powerview-shade-gen3.groovy, commenting out the throws in the supportsXXX functions makes the code work perfectly.

**Comment by bujvary** [comment]
Replaced all exceptions with log.debug
